### ISSUE TITLE
Screen randomly zooms in

### ISSUE THREAD

**Issue by JVTEAM** [taoteh1221/Slideshow_Crypto_Ticker#45]
After a few hours of use the screen zooms in at random intervals making it unreadable.  Stopping and restarting the ticker fixes it.

**Comment by taoteh1221** [comment]
@JVTEAM What browser are you using? The latest versions have support for chromium / epiphany / firefox / midori. I need to know which you are using to try and replicate the issue.

**Comment by JVTEAM** [comment]
> @JVTEAM What browser are you using? The latest versions have support for chromium / epiphany / firefox / midori. I need to know which you are using to try and replicate the issue.

Chromium.  It's an official RPI  touchscreen with an RPI3b.  I reinstalled to the newest version today, but it still happened.  However, I realized that I can pinch the screen back to normal size after it happens.  I wonder if there is a way to disable the touchscreen while the ticker is active.

**Comment by taoteh1221** [comment]
Thanks for the info. I'm releasing a patch for chromium on raspberry pi devices today, based off the issue here in their github repo: https://github.com/RPi-Distro/chromium-browser/issues/28

Let's see if this patched version helps you before trying other things. It should be in an hour or two, just grabbing a bite to eat before a final code review. I'll ping you here when v3.09.5 is released. :+1:

**Comment by taoteh1221** [comment]
Just released v3.09.5: 

https://github.com/taoteh1221/Slideshow_Crypto_Ticker/releases

Let me know if you still have issues with this release, we'll figure out the best solution if so. 

Thanks for the feedback! :smile:

**Comment by taoteh1221** [comment]
@JVTEAM Is the screen automatically zooming still an issue in the latest version (3.09.5)?
