### ISSUE TITLE
ticker showing zoomed in and not visible.

### ISSUE THREAD

**Issue by davehorner** [taoteh1221/Slideshow_Crypto_Ticker#58]
Thanks for the software!

I found that it worked well for some time, I'm not sure what happened but now it is displaying only a portion of the text, which is all zoomed in.

It displays for a second where I can see most things:
<img width="728" alt="image" src="https://github.com/taoteh1221/Open_Crypto_Tracker/assets/140924/d5345c08-693c-409d-bfa0-07d75b5c6548">

Then I am zoomed way in and there is a scrollbar on the right side which I can use to scroll up and down, all the content is there.
<img width="572" alt="image" src="https://github.com/taoteh1221/Open_Crypto_Tracker/assets/140924/db26695c-4c89-48fd-a886-5d694af03351">

I am seeing this behavior on the HDMI and using RealVNC.  I have changed the config to add some coins and flip the orientation.

I am using firefox and using Raspbian.

Or I should say the output indicates it is using firefox, but as you can see from my screen shot above, it looks like google is being used.
```
./ticker-start
server does not have extension for -dpms option
unclutter: someone created a sub-window to my sub-window! giving up
 
Browser not specified, using default browser firefox...
```

**Comment by taoteh1221** [comment]
> ```
> sudo update-alternatives --config x-www-browser
> ```
> 
> I selected firefox and I can see that firefox is being launched. However, the issue persists.

Hmmm. So the first thing I need to determine is why are you using RealVNC in your particular environment? There is no need for it usually, unless you need the display to be remotely connected for some reason (instead of wired).

Second, see where it says "RealVNC Viewer"? Is it using chromium as it's viewer I wonder? If so, your always going to see it open in that when using RealVNC. 

Third, I'm pretty sure this extra layer of routing through RealVNC is the issue. Can you connect the HDMI display directly to the raspberry pi? This is how I developed / debugged this app to run (with an HDMI cable plugged into the pi device).

Just saw this at the end of my work day checking my email, so I'm headed offline now until Sunday morning USA Eastern time, but I'll look for any responses from you Sunday morning. Thanks for taking the time to report with this feedback, I appreciate it.

**Comment by davehorner** [comment]
There is no need for the VNC, only to give you screenshots and letting me have the ticker from my pc in the next room.
It is also showing the same errant behavior on the HDMI.  I haven't bought an LCD yet but I will let you know.
I will play with vnc turning it off and on and other things.  If you have suggestions on where to look in the code or other ideas, lmk.

thanks for the software. its cool.

**Comment by taoteh1221** [comment]
I appreciate the effort to show using RealVNC, but this actually does the opposite of help me figure out what is going on. A photo of it running on an HDMI display of some sort will let me know what's going on way better. That said, if it's too big on a normal display too, just adjust the title / ticker / trade volume text sizes in config.js (see the recommended sizes in the notes next to each setting).

**Comment by taoteh1221** [comment]
If it got larger immediately after upgrading it, it's the text sizes in the config.js files. Shoot a photo on your phone and post it, if it still gives you issues after adjustment of text sizes. Then I can figure out what's really going on.

**Comment by davehorner** [comment]
I said that it was the same on the HDMI.  I didn't take the picture of my physical TV because I thought it was clear.  Didn't mean it make it harder on you, just communicating the behavior to you.

I'd like for it to work in VNC.

I will try and play with this sometime this weekend.  thanks for the suggestion I will look closer.

**Comment by davehorner** [comment]
Lots of flexibility there in the sizes.  With some adjustments I was able to get it working on my tv and vnc.  Thank you.

**Comment by taoteh1221** [comment]
> I said that it was the same on the HDMI. I didn't take the picture of my physical TV because I thought it was clear. Didn't mean it make it harder on you, just communicating the behavior to you.
> 
> I'd like for it to work in VNC.
> 
> I will try and play with this sometime this weekend. thanks for the suggestion I will look closer.

The more info you can give me, the better. "It's broke" doesn't really help me pin down what's going on, and not seeing exactly what it looks like on the ATTACHED screen with a photo does not help. The problem is, I have zero issues on my installation, so I need to pinpoint what's different with your setup. Otherwise, there is nothing I can do to help you fix it. 

It sounds like your problem was upgrading to the latest version, in which I default to support for large displays (10 inches). Glad you got it figured out.
